fn main() {
    println!("cargo:rerun-if-env-changed=TAURI_UPDATER_PUBLIC_KEY");
    if let Ok(public_key) = std::env::var("TAURI_UPDATER_PUBLIC_KEY") {
        println!("cargo:rustc-env=TAURI_UPDATER_PUBLIC_KEY={public_key}");
    }

    let notice_path = std::path::Path::new("resources/licenses/THIRD_PARTY_NOTICES.txt");
    if let Some(parent) = notice_path.parent() {
        std::fs::create_dir_all(parent).expect("failed to create license resource directory");
    }
    if !notice_path.exists() {
        std::fs::write(
            notice_path,
            "Third-party notices are generated by npm run build.\n",
        )
        .expect("failed to create placeholder third-party notice file");
    }
    tauri_build::build();
}
