[package]
name = "vrcx-0-runtime-host"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Shared runtime composition"

[features]
default = []
test-utils = [
    "vrcx-0-application/test-utils",
    "vrcx-0-application-core/test-utils",
    "vrcx-0-application-realtime/test-utils"
]

[dependencies]
chrono = { workspace = true }
iana-time-zone.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta.workspace = true
sys-locale.workspace = true
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "rt", "macros", "sync"] }
tracing = { workspace = true }
url = { workspace = true }
vrcx-0-application = { path = "../application" }
vrcx-0-application-activity = { path = "../application-activity" }
vrcx-0-application-core = { path = "../application-core" }
vrcx-0-application-realtime = { path = "../application-realtime" }
vrcx-0-core = { path = "../core" }
vrcx-0-host = { path = "../host" }
vrcx-0-integrations = { path = "../integrations" }
vrcx-0-i18n = { path = "../i18n" }
vrcx-0-media = { path = "../media" }
vrcx-0-persistence = { path = "../persistence" }
vrcx-0-vrchat-client = { path = "../vrchat-client" }
uuid.workspace = true

[dev-dependencies]
vrcx-0-application-realtime = { path = "../application-realtime", features = ["test-utils"] }
