[package]
name = "vrcx-0-vr-overlay"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "VR overlay UI"
build = "build.rs"

[features]
default = []
friends-panel = []
slint-ui = ["dep:slint"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
slint = { workspace = true, optional = true }
specta.workspace = true

[build-dependencies]
slint-build.workspace = true
