pub(super) const NOTIFICATION_V1_COLUMNS: &[&str] = &[
    "id",
    "created_at",
    "type",
    "sender_user_id",
    "sender_username",
    "receiver_user_id",
    "message",
    "world_id",
    "world_name",
    "image_url",
    "invite_message",
    "request_message",
    "response_message",
    "expired",
];

pub(super) const NOTIFICATION_V2_COLUMNS: &[&str] = &[
    "id",
    "created_at",
    "updated_at",
    "expires_at",
    "type",
    "link",
    "link_text",
    "message",
    "title",
    "image_url",
    "seen",
    "sender_user_id",
    "sender_username",
    "data",
    "responses",
    "details",
];
