name: Feature Request
description: Suggest an idea for this project
labels:
    - enhancement
body:
    - type: markdown
      attributes:
          value: |
              Thank you for submitting an idea.

              You may join our [Discord](https://discord.gg/fehKP3SVPN) server for further conversation and support.

    - type: textarea
      attributes:
          label: What feature would you like to see?
          description: Provide a clear and concise description of the feature.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Why would this feature be useful?
          description: Explain the use case or the problem it solves.
    - type: textarea
      attributes:
          label: Additional Context
          description: |
              Attach screenshots, examples, or anything else that might help.
