import mediaApiRepository, {
    consumeInventoryBundle,
    deleteFile,
    deletePrint,
    executeDelete,
    executeFilePut,
    executeGet,
    executeRequest,
    getFileList,
    getFiles,
    getInventoryItems,
    getPrint,
    getPrints,
    getUserInventoryItem,
    redeemReward,
    uploadAvatarGalleryImage,
    uploadAvatarImageLegacy,
    uploadEmoji,
    uploadGalleryImage,
    uploadImage,
    uploadPrint,
    uploadSticker,
    uploadVrcPlusIcon,
    uploadWorldImageLegacy
} from './mediaApiRepository.js';
import mediaFileRepository, {
    addScreenshotMetadata,
    copyImageToClipboard,
    cropAllPrints,
    cropPrintImage,
    deleteScreenshotMetadata,
    findScreenshotsBySearch,
    getExtraScreenshotData,
    getFileBase64,
    getLastScreenshot,
    getScreenshotMetadata,
    getUgcPhotoLocation,
    getVrchatPhotosLocation,
    invokeApp,
    openFileSelectorDialog,
    openFolderAndSelectItem,
    resizeImageToFitLimits,
    saveEmojiToFile,
    saveImageFile,
    savePrintToFile,
    saveStickerToFile
} from './mediaFileRepository.js';

type MediaRepository = typeof mediaApiRepository & typeof mediaFileRepository;

const mediaRepository = Object.freeze({
    ...mediaApiRepository,
    ...mediaFileRepository
}) as MediaRepository;

export {
    executeFilePut,
    executeRequest,
    executeGet,
    executeDelete,
    uploadImage,
    getFiles,
    getFileList,
    deleteFile,
    uploadGalleryImage,
    uploadAvatarGalleryImage,
    uploadVrcPlusIcon,
    uploadEmoji,
    uploadSticker,
    uploadPrint,
    getPrints,
    getPrint,
    deletePrint,
    getInventoryItems,
    getUserInventoryItem,
    consumeInventoryBundle,
    redeemReward,
    resizeImageToFitLimits,
    uploadAvatarImageLegacy,
    uploadWorldImageLegacy,
    invokeApp,
    getFileBase64,
    getScreenshotMetadata,
    deleteScreenshotMetadata,
    addScreenshotMetadata,
    getExtraScreenshotData,
    findScreenshotsBySearch,
    getLastScreenshot,
    getVrchatPhotosLocation,
    getUgcPhotoLocation,
    openFileSelectorDialog,
    openFolderAndSelectItem,
    copyImageToClipboard,
    saveImageFile,
    savePrintToFile,
    saveStickerToFile,
    saveEmojiToFile,
    cropPrintImage,
    cropAllPrints
};

export default mediaRepository;
