[package]
name = "vrcx-0-application"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Application business services"

[features]
test-utils = [
    "vrcx-0-application-core/test-utils",
    "vrcx-0-application-realtime/test-utils"
]

[dependencies]
chrono = { workspace = true }
base64 = { workspace = true }
futures-util = "0.3"
hex = "0.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = [
    "rt",
    "macros",
    "sync",
    "time"
] }
tracing = { workspace = true }
vrcx-0-core = { path = "../core" }
vrcx-0-application-core = { path = "../application-core" }
vrcx-0-application-realtime = { path = "../application-realtime" }
vrcx-0-integrations = { path = "../integrations" }
vrcx-0-media = { path = "../media" }
vrcx-0-persistence = { path = "../persistence" }
vrcx-0-vrchat-client = { path = "../vrchat-client" }
specta.workspace = true

[dev-dependencies]
async-trait = { workspace = true }
image = { workspace = true }
rusqlite = { workspace = true, features = ["bundled"] }
vrcx-0-application-core = { path = "../application-core", features = ["test-utils"] }
vrcx-0-application-realtime = { path = "../application-realtime", features = ["test-utils"] }
