[package]
name = "vrcx-0-vrchat-client"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "VRChat API client"

[dependencies]
base64 = { workspace = true }
hyper-util = { version = "0.1.20", features = ["client-legacy", "tokio"] }
percent-encoding = { workspace = true }
reqwest = { workspace = true, features = [
    "cookies",
    "gzip",
    "brotli",
    "deflate",
    "multipart",
    "socks"
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta.workspace = true
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util"] }
tokio-tungstenite = { version = "0.30", features = ["rustls-tls-native-roots"] }
tower-service = "0.3"
tracing = { workspace = true }
url = { workspace = true }
vrcx-0-core = { path = "../core" }
cookie_store = "0.22.1"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
