[package]
name = "vrcx-0-application-game"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Desktop game runtime"

[features]
test-utils = [
    "vrcx-0-application-activity/test-utils",
    "vrcx-0-application-core/test-utils",
]

[dependencies]
chrono = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tracing = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }
vrcx-0-application-activity = { path = "../application-activity" }
vrcx-0-application-core = { path = "../application-core" }
vrcx-0-core = { path = "../core" }
vrcx-0-integrations = { path = "../integrations" }
vrcx-0-media = { path = "../media" }
vrcx-0-persistence = { path = "../persistence" }
vrcx-0-vrchat-client = { path = "../vrchat-client" }

[dev-dependencies]
image = { workspace = true }
rusqlite = { workspace = true }
vrcx-0-application-core = { path = "../application-core", features = ["test-utils"] }
vrcx-0-i18n = { path = "../i18n" }
