name: Preview

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-preview
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    package:
        name: Package Preview
        uses: ./.github/workflows/_package-variant.yml
        with:
            variant: preview
